name: Generate JSON Files from List Files

on:
  push:
    paths:
      - "*.list"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # Grant write permissions for the repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install json5

      - name: Run Python Script
        run: python generate_json.py

      - name: Debug Generated Files
        run: ls -l *.json || echo "No JSON files found."

      - name: Add generated files to staging
        run: |
          git add *.json
          git diff-index --cached --quiet HEAD || echo "Files added to staging."

      - name: Commit changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Update JSON files from list files"
          fi

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref_name }} # Use GITHUB_TOKEN implicitly
