name: Generate JSON Files from List Files

on:
  push:
    paths:
      - "*.list"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install json5

      - name: Run Python Script
        run: python generate_json.py

      - name: Debug Generated Files
        run: ls -l *.json

      - name: Check Git Status
        run: git status

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update JSON files from list files"
            git push "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
          fi
