name: Generate JSON Files from List Files

on:
  push:
    paths:
      - "*.list"  # 监控所有 .list 文件的变更

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install json5

      - name: Run Python Script
        run: python generate_json.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json
          git commit -m "Update JSON files from list files"
          git push
