name: Generate JSON Files from List Files

on:
  push:
    paths:
      - "*.list"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整提交历史
          ref: ${{ github.ref }}  # 显式指定引用

      # 添加关键的准备步骤
      - name: Configure Git Safety
        run: |
          # 禁用自动换行转换（避免CRLF问题）
          git config --global core.autocrlf false
          # 允许历史不相干的仓库合并
          git config --global pull.rebase true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install json5

      # 添加强制同步步骤
      - name: Force Synchronize with Remote
        run: |
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}
          git clean -fd

      # 在同步后重新生成文件
      - name: Run Python Script
        run: python generate_json.py

      - name: Add generated files to staging
        run: |
          git add -u  # 更新所有已跟踪文件的变更
          git add *.json  # 添加新生成的 JSON 文件
          git status  # 显示状态确认

      - name: Commit changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Automated JSON update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          fi

      # 强化推送步骤
      - name: Push changes
        run: |
          attempt=0
          max_attempts=3
          until [ $attempt -ge $max_attempts ]; do
            git pull --rebase origin ${{ github.ref_name }}
            if git push origin HEAD:${{ github.ref_name }}; then
              echo "Push succeeded!"
              exit 0
            else
              attempt=$((attempt + 1))
              echo "Push attempt $attempt failed. Retrying..."
              sleep 5
            fi
          done
          echo "All push attempts failed. Manual intervention required."
          exit 1
